#!/bin/bash

#Format changed files
changed_files=$(git diff --cached --name-only -- '*.c' '*.h')

if [ -n "$changed_files" ]; then
    echo "* Formatting changed files"
    make format
    git add $changed_files
fi
