name: Check-Format

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Formatter
        uses: actions/cache@v4
        id: clang-format-cache
        with:
          key: clang-format-${{ runner.os }}
          path: ${{ github.workspace }}/bin

      - name: Install Formatter
        if: ${{ steps.clang-format-cache.outputs.cache-hit != 'true' }}
        run: |
          mkdir -p ${{ github.workspace }}/bin
          PIPX_BIN_DIR=${{ github.workspace }}/bin ./tools/format.sh --install

      - name: Add Formatter to Path
        run: echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Make
        run: make check-format
